// <auto-generated />
using System;
using FinancialImport.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable enable

namespace FinancialImport.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260407000000_InitialCreate")]
partial class InitialCreate
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

        modelBuilder.Entity("FinancialImport.Domain.Entities.BranchMapping", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName("Id");
            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));
            b.Property<int>("BplId").HasColumnType("int").HasColumnName("BPLId");
            b.Property<string>("BranchName").IsRequired().HasMaxLength(120).HasColumnType("varchar(120)").HasColumnName("NomeFilial");
            b.Property<string>("CompanyDb").IsRequired().HasMaxLength(50).HasColumnType("varchar(50)").HasColumnName("CompanyDb");
            b.Property<string>("FileBranchCode").IsRequired().HasMaxLength(20).HasColumnType("varchar(20)").HasColumnName("CodigoFilialArquivo");
            b.Property<bool>("IsActive").HasColumnType("tinyint(1)").HasColumnName("Ativo");
            b.HasKey("Id");
            b.HasIndex("CompanyDb", "FileBranchCode").IsUnique();
            b.ToTable("MapeamentoFilialSap", (string)null);
        });

        modelBuilder.Entity("FinancialImport.Domain.Entities.CompanyUserSession", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName("Id");
            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));
            b.Property<string>("CompanyDb").IsRequired().HasMaxLength(50).HasColumnType("varchar(50)").HasColumnName("CompanyDb");
            b.Property<string>("CompanyName").IsRequired().HasMaxLength(120).HasColumnType("varchar(120)").HasColumnName("CompanyName");
            b.Property<DateTime>("ExpiresAt").HasColumnType("datetime(6)").HasColumnName("ExpiraEm");
            b.Property<bool>("IsActive").HasColumnType("tinyint(1)").HasColumnName("Ativa");
            b.Property<DateTime>("LoginAt").HasColumnType("datetime(6)").HasColumnName("DataLogin");
            b.Property<string>("RouteId").HasMaxLength(120).HasColumnType("varchar(120)").HasColumnName("RouteId");
            b.Property<string>("SapUserName").IsRequired().HasMaxLength(80).HasColumnType("varchar(80)").HasColumnName("SapUserName");
            b.Property<string>("SessionId").IsRequired().HasMaxLength(120).HasColumnType("varchar(120)").HasColumnName("SessionId");
            b.Property<long>("UserId").HasColumnType("bigint").HasColumnName("UsuarioId");
            b.HasKey("Id");
            b.HasIndex("CompanyDb");
            b.HasIndex("UserId");
            b.ToTable("SessaoEmpresaUsuario", (string)null);
        });

        modelBuilder.Entity("FinancialImport.Domain.Entities.ImportFile", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName("Id");
            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));
            b.Property<string>("BranchDefault").HasMaxLength(20).HasColumnType("varchar(20)").HasColumnName("FilialPadrao");
            b.Property<string>("CompanyDb").IsRequired().HasMaxLength(50).HasColumnType("varchar(50)").HasColumnName("CompanyDb");
            b.Property<int>("DuplicatedLines").HasColumnType("int").HasColumnName("QuantidadeDuplicadas");
            b.Property<string>("FileHash").IsRequired().HasMaxLength(64).HasColumnType("varchar(64)").HasColumnName("HashArquivo");
            b.Property<DateTime>("ImportedAt").HasColumnType("datetime(6)").HasColumnName("DataImportacao");
            b.Property<int>("ImportedLines").HasColumnType("int").HasColumnName("QuantidadeImportadas");
            b.Property<int>("InvalidLines").HasColumnType("int").HasColumnName("QuantidadeInvalidas");
            b.Property<string>("LayoutDetected").IsRequired().HasMaxLength(80).HasColumnType("varchar(80)").HasColumnName("LayoutDetectado");
            b.Property<int>("LinesWithError").HasColumnType("int").HasColumnName("QuantidadeComErro");
            b.Property<string>("OriginalFileName").IsRequired().HasMaxLength(200).HasColumnType("varchar(200)").HasColumnName("NomeArquivoOriginal");
            b.Property<string>("Status").IsRequired().HasMaxLength(40).HasColumnType("varchar(40)").HasColumnName("Status");
            b.Property<int>("TotalLines").HasColumnType("int").HasColumnName("QuantidadeLinhas");
            b.Property<bool>("UseBranchFromFile").HasColumnType("tinyint(1)").HasColumnName("UsarFilialArquivo");
            b.Property<long>("UserId").HasColumnType("bigint").HasColumnName("UsuarioId");
            b.Property<int>("ValidLines").HasColumnType("int").HasColumnName("QuantidadeValidas");
            b.HasKey("Id");
            b.HasIndex("CompanyDb");
            b.HasIndex("UserId");
            b.HasIndex("CompanyDb", "FileHash").IsUnique();
            b.ToTable("ImportacaoArquivo", (string)null);
        });

        modelBuilder.Entity("FinancialImport.Domain.Entities.ImportLine", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName("Id");
            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));
            b.Property<string>("AccountCode").IsRequired().HasMaxLength(30).HasColumnType("varchar(30)").HasColumnName("ContaContabil");
            b.Property<decimal>("Amount").HasColumnType("decimal(18,2)").HasColumnName("Valor");
            b.Property<string>("BranchCode").HasMaxLength(20).HasColumnType("varchar(20)").HasColumnName("Filial");
            b.Property<string>("BusinessKeyHash").IsRequired().HasMaxLength(64).HasColumnType("varchar(64)").HasColumnName("HashChaveNegocio");
            b.Property<string>("CompanyDb").IsRequired().HasMaxLength(50).HasColumnType("varchar(50)").HasColumnName("CompanyDb");
            b.Property<string>("ContraAccountCode").IsRequired().HasMaxLength(30).HasColumnType("varchar(30)").HasColumnName("ContaContrapartida");
            b.Property<decimal?>("CreditAmount").HasColumnType("decimal(18,2)").HasColumnName("ValorCredito");
            b.Property<decimal?>("DebitAmount").HasColumnType("decimal(18,2)").HasColumnName("ValorDebito");
            b.Property<DateTime>("DocumentDate").HasColumnType("datetime(6)").HasColumnName("DataDocumento");
            b.Property<DateTime>("DueDate").HasColumnType("datetime(6)").HasColumnName("DataVencimento");
            b.Property<long>("ImportFileId").HasColumnType("bigint").HasColumnName("ImportacaoArquivoId");
            b.Property<string>("LineHash").IsRequired().HasMaxLength(64).HasColumnType("varchar(64)").HasColumnName("HashLinha");
            b.Property<string>("LineMemo").IsRequired().HasMaxLength(200).HasColumnType("varchar(200)").HasColumnName("HistoricoLinha");
            b.Property<DateTime>("PostingDate").HasColumnType("datetime(6)").HasColumnName("DataLancamento");
            b.Property<string>("Reference").IsRequired().HasMaxLength(120).HasColumnType("varchar(120)").HasColumnName("Referencia");
            b.Property<int?>("SapDocEntry").HasColumnType("int").HasColumnName("DocEntrySap");
            b.Property<string>("SapReturnMessage").HasMaxLength(400).HasColumnType("varchar(400)").HasColumnName("MensagemRetornoSap");
            b.Property<string>("SeqLancamento").HasMaxLength(60).HasColumnType("varchar(60)").HasColumnName("SeqLancamento");
            b.Property<string>("SourceJson").HasColumnType("json").HasColumnName("JsonOrigem");
            b.Property<string>("Status").IsRequired().HasMaxLength(40).HasColumnType("varchar(40)").HasColumnName("Status");
            b.Property<string>("ValidationMessage").HasMaxLength(400).HasColumnType("varchar(400)").HasColumnName("MensagemValidacao");
            b.HasKey("Id");
            b.HasIndex("ImportFileId");
            b.HasIndex("CompanyDb", "BusinessKeyHash").IsUnique();
            b.ToTable("ImportacaoLinha", (string)null);
        });

        modelBuilder.Entity("FinancialImport.Domain.Entities.LayoutConfig", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName("Id");
            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));
            b.Property<string>("Description").HasMaxLength(200).HasColumnType("varchar(200)").HasColumnName("Descricao");
            b.Property<bool>("IsActive").HasColumnType("tinyint(1)").HasColumnName("Ativo");
            b.Property<string>("LayoutName").IsRequired().HasMaxLength(80).HasColumnType("varchar(80)").HasColumnName("NomeLayout");
            b.HasKey("Id");
            b.HasIndex("LayoutName").IsUnique();
            b.ToTable("ConfiguracaoLayout", (string)null);
        });

        modelBuilder.Entity("FinancialImport.Domain.Entities.LayoutFieldConfig", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName("Id");
            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));
            b.Property<string>("DataType").IsRequired().HasMaxLength(40).HasColumnType("varchar(40)").HasColumnName("TipoDado");
            b.Property<string>("InternalFieldName").IsRequired().HasMaxLength(120).HasColumnType("varchar(120)").HasColumnName("NomeCampoInterno");
            b.Property<bool>("IsRequired").HasColumnType("tinyint(1)").HasColumnName("Obrigatorio");
            b.Property<long>("LayoutId").HasColumnType("bigint").HasColumnName("LayoutId");
            b.Property<int>("Order").HasColumnType("int").HasColumnName("Ordem");
            b.Property<string>("SourceColumnName").IsRequired().HasMaxLength(120).HasColumnType("varchar(120)").HasColumnName("NomeColunaOrigem");
            b.HasKey("Id");
            b.HasIndex("LayoutId");
            b.ToTable("ConfiguracaoLayoutCampo", (string)null);
        });

        modelBuilder.Entity("FinancialImport.Domain.Entities.LoginAudit", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName("Id");
            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));
            b.Property<string>("FailureReason").HasMaxLength(200).HasColumnType("varchar(200)").HasColumnName("MotivoFalha");
            b.Property<string>("IpAddress").HasMaxLength(64).HasColumnType("varchar(64)").HasColumnName("EnderecoIp");
            b.Property<string>("LoginProvided").IsRequired().HasMaxLength(80).HasColumnType("varchar(80)").HasColumnName("LoginInformado");
            b.Property<DateTime>("OccurredAt").HasColumnType("datetime(6)").HasColumnName("DataHora");
            b.Property<bool>("Success").HasColumnType("tinyint(1)").HasColumnName("Sucesso");
            b.Property<string>("UserAgent").HasMaxLength(200).HasColumnType("varchar(200)").HasColumnName("UserAgent");
            b.Property<long?>("UserId").HasColumnType("bigint").HasColumnName("UsuarioId");
            b.HasKey("Id");
            b.HasIndex("OccurredAt");
            b.HasIndex("UserId");
            b.ToTable("AuditoriaLogin", (string)null);
        });

        modelBuilder.Entity("FinancialImport.Domain.Entities.Permission", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName("Id");
            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));
            b.Property<string>("Code").IsRequired().HasMaxLength(80).HasColumnType("varchar(80)").HasColumnName("Codigo");
            b.Property<string>("Description").HasMaxLength(200).HasColumnType("varchar(200)").HasColumnName("Descricao");
            b.Property<string>("Group").HasMaxLength(80).HasColumnType("varchar(80)").HasColumnName("Grupo");
            b.Property<bool>("IsActive").HasColumnType("tinyint(1)").HasColumnName("Ativo");
            b.Property<string>("Name").IsRequired().HasMaxLength(120).HasColumnType("varchar(120)").HasColumnName("Nome");
            b.HasKey("Id");
            b.HasIndex("Code").IsUnique();
            b.ToTable("Permissoes", (string)null);
        });

        modelBuilder.Entity("FinancialImport.Domain.Entities.Profile", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName("Id");
            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));
            b.Property<string>("Description").HasMaxLength(200).HasColumnType("varchar(200)").HasColumnName("Descricao");
            b.Property<bool>("IsActive").HasColumnType("tinyint(1)").HasColumnName("Ativo");
            b.Property<string>("Name").IsRequired().HasMaxLength(80).HasColumnType("varchar(80)").HasColumnName("Nome");
            b.HasKey("Id");
            b.HasIndex("Name").IsUnique();
            b.ToTable("Perfis", (string)null);
        });

        modelBuilder.Entity("FinancialImport.Domain.Entities.ProfilePermission", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName("Id");
            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));
            b.Property<long>("PermissionId").HasColumnType("bigint").HasColumnName("PermissaoId");
            b.Property<long>("ProfileId").HasColumnType("bigint").HasColumnName("PerfilId");
            b.HasKey("Id");
            b.HasIndex("ProfileId", "PermissionId").IsUnique();
            b.ToTable("PerfilPermissao", (string)null);
        });

        modelBuilder.Entity("FinancialImport.Domain.Entities.Rule", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName("Id");
            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));
            b.Property<bool>("IsActive").HasColumnType("tinyint(1)").HasColumnName("Ativo");
            b.Property<string>("Key").IsRequired().HasMaxLength(120).HasColumnType("varchar(120)").HasColumnName("Chave");
            b.Property<string>("ScopeCompanyDb").HasMaxLength(50).HasColumnType("varchar(50)").HasColumnName("EscopoCompanyDb");
            b.Property<string>("Value").IsRequired().HasMaxLength(400).HasColumnType("varchar(400)").HasColumnName("Valor");
            b.HasKey("Id");
            b.HasIndex("Key").IsUnique();
            b.ToTable("Regras", (string)null);
        });

        modelBuilder.Entity("FinancialImport.Domain.Entities.SystemLog", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName("Id");
            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));
            b.Property<string>("CompanyDb").HasMaxLength(50).HasColumnType("varchar(50)").HasColumnName("CompanyDb");
            b.Property<string>("CorrelationId").HasMaxLength(60).HasColumnType("varchar(60)").HasColumnName("CorrelationId");
            b.Property<string>("Details").HasColumnType("longtext").HasColumnName("Detalhes");
            b.Property<string>("Level").IsRequired().HasMaxLength(20).HasColumnType("varchar(20)").HasColumnName("Nivel");
            b.Property<string>("Message").IsRequired().HasMaxLength(400).HasColumnType("varchar(400)").HasColumnName("Mensagem");
            b.Property<DateTime>("OccurredAt").HasColumnType("datetime(6)").HasColumnName("DataHora");
            b.Property<string>("Source").IsRequired().HasMaxLength(80).HasColumnType("varchar(80)").HasColumnName("Origem");
            b.Property<long?>("UserId").HasColumnType("bigint").HasColumnName("UsuarioId");
            b.HasKey("Id");
            b.HasIndex("OccurredAt");
            b.HasIndex("UserId");
            b.ToTable("LogSistema", (string)null);
        });

        modelBuilder.Entity("FinancialImport.Domain.Entities.User", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName("Id");
            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)").HasColumnName("DataCriacao");
            b.Property<string>("CreatedBy").IsRequired().HasMaxLength(80).HasColumnType("varchar(80)").HasColumnName("UsuarioCriacao");
            b.Property<string>("Email").IsRequired().HasMaxLength(120).HasColumnType("varchar(120)").HasColumnName("Email");
            b.Property<bool>("IsActive").HasColumnType("tinyint(1)").HasColumnName("Ativo");
            b.Property<bool>("IsBlocked").HasColumnType("tinyint(1)").HasColumnName("Bloqueado");
            b.Property<bool>("IsGlobalAdmin").ValueGeneratedOnAdd().HasColumnType("tinyint(1)").HasDefaultValue(false).HasColumnName("AdminGlobal");
            b.Property<DateTime?>("LastLoginAt").HasColumnType("datetime(6)").HasColumnName("DataUltimoLogin");
            b.Property<string>("Login").IsRequired().HasMaxLength(80).HasColumnType("varchar(80)").HasColumnName("Login");
            b.Property<string>("Name").IsRequired().HasMaxLength(120).HasColumnType("varchar(120)").HasColumnName("Nome");
            b.Property<byte[]>("PasswordHash").IsRequired().HasColumnType("varbinary(256)").HasColumnName("SenhaHash");
            b.Property<byte[]>("PasswordSalt").HasColumnType("varbinary(128)").HasColumnName("SenhaSalt");
            b.HasKey("Id");
            b.HasIndex("Email").IsUnique();
            b.HasIndex("Login").IsUnique();
            b.ToTable("Usuarios", (string)null);
        });

        modelBuilder.Entity("FinancialImport.Domain.Entities.UserCompanyPermission", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName("Id");
            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));
            b.Property<string>("CompanyDb").IsRequired().HasMaxLength(50).HasColumnType("varchar(50)").HasColumnName("CompanyDb");
            b.Property<bool>("IsActive").HasColumnType("tinyint(1)").HasColumnName("Ativo");
            b.Property<long>("UserId").HasColumnType("bigint").HasColumnName("UsuarioId");
            b.HasKey("Id");
            b.HasIndex("UserId", "CompanyDb").IsUnique();
            b.ToTable("UsuarioEmpresaPermitida", (string)null);
        });

        modelBuilder.Entity("FinancialImport.Domain.Entities.UserProfile", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName("Id");
            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));
            b.Property<long>("ProfileId").HasColumnType("bigint").HasColumnName("PerfilId");
            b.Property<long>("UserId").HasColumnType("bigint").HasColumnName("UsuarioId");
            b.HasKey("Id");
            b.HasIndex("UserId", "ProfileId").IsUnique();
            b.ToTable("UsuarioPerfil", (string)null);
        });

        // FK relationships
        modelBuilder.Entity("FinancialImport.Domain.Entities.CompanyUserSession", b =>
        {
            b.HasOne("FinancialImport.Domain.Entities.User", "User")
                .WithMany("CompanySessions")
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("User");
        });

        modelBuilder.Entity("FinancialImport.Domain.Entities.ImportFile", b =>
        {
            b.HasOne("FinancialImport.Domain.Entities.User", "User")
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
            b.Navigation("User");
        });

        modelBuilder.Entity("FinancialImport.Domain.Entities.ImportLine", b =>
        {
            b.HasOne("FinancialImport.Domain.Entities.ImportFile", "ImportFile")
                .WithMany("Lines")
                .HasForeignKey("ImportFileId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("ImportFile");
        });

        modelBuilder.Entity("FinancialImport.Domain.Entities.LayoutFieldConfig", b =>
        {
            b.HasOne("FinancialImport.Domain.Entities.LayoutConfig", "Layout")
                .WithMany("Fields")
                .HasForeignKey("LayoutId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Layout");
        });

        modelBuilder.Entity("FinancialImport.Domain.Entities.LoginAudit", b =>
        {
            b.HasOne("FinancialImport.Domain.Entities.User", "User")
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.SetNull);
            b.Navigation("User");
        });

        modelBuilder.Entity("FinancialImport.Domain.Entities.ProfilePermission", b =>
        {
            b.HasOne("FinancialImport.Domain.Entities.Permission", "Permission")
                .WithMany("Profiles")
                .HasForeignKey("PermissionId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.HasOne("FinancialImport.Domain.Entities.Profile", "Profile")
                .WithMany("Permissions")
                .HasForeignKey("ProfileId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Permission");
            b.Navigation("Profile");
        });

        modelBuilder.Entity("FinancialImport.Domain.Entities.UserCompanyPermission", b =>
        {
            b.HasOne("FinancialImport.Domain.Entities.User", "User")
                .WithMany("AllowedCompanies")
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("User");
        });

        modelBuilder.Entity("FinancialImport.Domain.Entities.UserProfile", b =>
        {
            b.HasOne("FinancialImport.Domain.Entities.Profile", "Profile")
                .WithMany("Users")
                .HasForeignKey("ProfileId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.HasOne("FinancialImport.Domain.Entities.User", "User")
                .WithMany("Profiles")
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Profile");
            b.Navigation("User");
        });

        // Collection navigations
        modelBuilder.Entity("FinancialImport.Domain.Entities.ImportFile", b =>
        {
            b.Navigation("Lines");
        });

        modelBuilder.Entity("FinancialImport.Domain.Entities.LayoutConfig", b =>
        {
            b.Navigation("Fields");
        });

        modelBuilder.Entity("FinancialImport.Domain.Entities.Permission", b =>
        {
            b.Navigation("Profiles");
        });

        modelBuilder.Entity("FinancialImport.Domain.Entities.Profile", b =>
        {
            b.Navigation("Permissions");
            b.Navigation("Users");
        });

        modelBuilder.Entity("FinancialImport.Domain.Entities.User", b =>
        {
            b.Navigation("AllowedCompanies");
            b.Navigation("CompanySessions");
            b.Navigation("Profiles");
        });
#pragma warning restore 612, 618
    }
}
