// <auto-generated />
using FinancialImport.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FinancialImport.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507000000_AddCostingCodeToImportLine")]
    partial class AddCostingCodeToImportLine
    {
    }
}
