// <auto-generated />
using FinancialImport.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FinancialImport.Infrastructure.Migrations
{
    // The designer file is intentionally minimal: EF Core's runtime
    // migration applier only needs the [Migration] attribute to order
    // and apply this script. The design-time BuildTargetModel override
    // is omitted so that `dotnet ef migrations add` will regenerate it
    // consistently against the latest AppDbContextModelSnapshot.
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409000000_AddMessagingAndRichLogs")]
    partial class AddMessagingAndRichLogs
    {
    }
}
