// <auto-generated />
using FinancialImport.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FinancialImport.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260409000001_AddSystemSettings")]
partial class AddSystemSettings
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
}
