// <auto-generated />
using FinancialImport.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FinancialImport.Infrastructure.Migrations
{
    // Minimal designer: only the [Migration] attribute is needed by EF Core's
    // runtime migration applier. dotnet ef migrations add regenerates this
    // file against the latest AppDbContextModelSnapshot.
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409000001_AddSystemSettings")]
    partial class AddSystemSettings
    {
    }
}
